"""add_starred_field

Revision ID: 0e1f82d77393
Revises: 147b07c55ed2
Create Date: 2026-09-05 12:40:23.874586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e1f82d77393'
down_revision: Union[str, Sequence[str], None] = '147b07c55ed2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vocabularies', sa.Column('is_starred', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vocabularies', 'is_starred')
    # ### end Alembic commands ###
