"""add_folder_path

Revision ID: 333a343ffc7b
Revises: fc3ef69a8f69
Create Date: 2026-09-05 14:30:24.912286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '333a343ffc7b'
down_revision: Union[str, Sequence[str], None] = 'fc3ef69a8f69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sets', sa.Column('folder_path', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sets', 'folder_path')
    # ### end Alembic commands ###
