"""init_db

Revision ID: 4d4eb4fe2351
Revises: 
Create Date: 2026-09-04 23:10:27.021197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d4eb4fe2351'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_exam_questions_id'), 'exam_questions', ['id'], unique=False)
    op.create_index(op.f('ix_exams_id'), 'exams', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exams_id'), table_name='exams')
    op.drop_index(op.f('ix_exam_questions_id'), table_name='exam_questions')
    # ### end Alembic commands ###
