"""add_srs

Revision ID: 7cd9f19441d8
Revises: d8c957c00e3c
Create Date: 2026-09-05 12:34:02.398160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cd9f19441d8'
down_revision: Union[str, Sequence[str], None] = 'd8c957c00e3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vocabularies', sa.Column('furigana', sa.String(length=255), nullable=True))
    op.add_column('vocabularies', sa.Column('repetition', sa.Integer(), nullable=True))
    op.add_column('vocabularies', sa.Column('ease_factor', sa.Float(), nullable=True))
    op.add_column('vocabularies', sa.Column('interval', sa.Integer(), nullable=True))
    op.add_column('vocabularies', sa.Column('next_review', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vocabularies', 'next_review')
    op.drop_column('vocabularies', 'interval')
    op.drop_column('vocabularies', 'ease_factor')
    op.drop_column('vocabularies', 'repetition')
    op.drop_column('vocabularies', 'furigana')
    # ### end Alembic commands ###
